version: '3.8'

volumes:
  chatbot_db_storage:
  chatbot_n8n_storage:

services:
  chatbot-n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: chatbot-n8n
    restart: always
    environment:
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${DOMAIN_NAME}/
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}

      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=chatbot-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}

      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-n8n.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.chatbot-n8n.entrypoints=websecure"
      - "traefik.http.routers.chatbot-n8n.tls.certresolver=myresolver"
      - "traefik.http.middlewares.chatbot-n8n.headers.SSLRedirect=true"
      - "traefik.http.middlewares.chatbot-n8n.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.chatbot-n8n.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.chatbot-n8n.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.chatbot-n8n.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.chatbot-n8n.headers.SSLHost=${DOMAIN_NAME}"
      - "traefik.http.middlewares.chatbot-n8n.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.chatbot-n8n.headers.STSPreload=true"
      - "traefik.http.routers.chatbot-n8n.middlewares=chatbot-n8n@docker"
    volumes:
      - chatbot_n8n_storage:/home/node/.n8n
    depends_on:
      - chatbot-postgres
    networks:
      - n8n_network

  chatbot-postgres:
    image: pgvector/pgvector:pg16
    container_name: chatbot-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - chatbot_db_storage:/var/lib/postgresql/data
    networks:
      - n8n_network

networks:
  n8n_network:
    external: true

