services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: n8n-local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n123
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432" # Aberto para você conectar o DBeaver
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-local-network

  redis:
    image: redis:7-alpine
    container_name: n8n-local-redis
    restart: unless-stopped
    ports:
      - "6379:6379" # Aberto para debug se precisar
    volumes:
      - local_redis_data:/data
    networks:
      - n8n-local-network

  n8n-editor:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-local-editor
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      
      # Conexão Banco
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n123

      # Queue Mode (Simulando a produção)
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      
      # Chave fixa para facilitar o teste local (não use em prod!)
      - N8N_ENCRYPTION_KEY=chave-secreta-local-123
    volumes:
      - local_n8n_data:/home/node/.n8n
    networks:
      - n8n-local-network
    depends_on:
      - postgres
      - redis

  n8n-worker:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-local-worker
    restart: unless-stopped
    command: worker --concurrency=5
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n123
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENCRYPTION_KEY=chave-secreta-local-123
    volumes:
      - local_n8n_data:/home/node/.n8n
    networks:
      - n8n-local-network
    depends_on:
      - postgres
      - redis

volumes:
  local_n8n_data:
  local_postgres_data:
  local_redis_data:

networks:
  n8n-local-network:
    driver: bridge
